test,ios: fix IB document compilation error
Upgrade test/ios/app-bundle/test.gyp to IPHONEOS_DEPLOYMENT_TARGET 7.0
to fix the following error: "Compiling IB documents for earlier than iOS
7 is no longer supported."